version: "3.9"

services:
  service-postgres:
    image: postgres:14
    container_name: proxy-db
    environment:
      POSTGRES_DB: "proxy"
      POSTGRES_USER: "proxy"
      POSTGRES_PASSWORD: "proxy"
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ~/proxy-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U proxy -d proxy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: kayetana-proxy-image:latest
    container_name: kayetana-proxy
    environment:
      DATABASE_URL: "postgres://proxy:proxy@service-postgres:5432/proxy"
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - service-postgres
